#!/bin/bash

############################################################
############ QIIME 2: ECOLOGICAL ANALYSES ##################
############################################################

#SBATCH --job-name=16S_ecology
#SBATCH -p standard-s
#SBATCH -A abchase_marine_0001
#SBATCH --mem=16G
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=04:00:00
#SBATCH --output=16S_ecology-%j.out
#SBATCH --error=16S_ecology-%j.err


# This script demonstrates several common downstream analyses
# that can be performed directly in QIIME 2.
#
# These include:
#
#   1. Filtering unwanted taxa
#   2. Inspecting the final ASV table
#   3. Visualizing taxonomic composition
#   4. Examining alpha rarefaction
#   5. Calculating alpha and beta diversity
#   6. Testing simple differences among groups
#   7. Exporting data for downstream analysis in R
#
# IMPORTANT:
#
# QIIME 2 is useful for generating and exploring these
# ecological metrics. For more flexible statistical models,
# visualization, and ecological inference, we generally move
# the processed data into R.


############################################################
################### LOAD QIIME 2 ############################
############################################################

source ~/.bashrc

conda activate qiime2-2022.8

# Record the software version in the output file.

qiime info


############################################################
################### SET DIRECTORIES #########################
############################################################

BASEDIR=/projects/abchase/CHANGE_ME/16S_analysis

cd "$BASEDIR"


############################################################
###################### FILE NAMES ###########################
############################################################

# Inputs generated by the previous QIIME 2 script.

TABLE=table-dada2.qza
TAXONOMY=taxonomy.qza
TREE=rooted-tree.qza
METADATA=MO18-metadata.txt


############################################################
############### FILTER UNWANTED TAXA ########################
############################################################

# Our 16S primers can amplify DNA that is not part of the
# bacterial/archaeal community we want to analyze.
#
# For example, chloroplasts and mitochondria contain
# evolutionarily derived bacterial ribosomal RNA genes.
#
# We therefore remove these sequences before ecological
# analyses.
#
# "Eukaryota" is also excluded here because the analysis is
# focused on bacterial and archaeal 16S sequences.
#
# IMPORTANT:
#
# The exact taxonomic labels depend on the reference database
# and classifier. Always inspect your taxonomy rather than
# blindly copying this list.

qiime taxa filter-table \
  --i-table "$TABLE" \
  --i-taxonomy "$TAXONOMY" \
  --p-exclude mitochondria,chloroplast,eukaryota \
  --o-filtered-table filtered-table.qza


############################################################
############ OPTIONAL FEATURE FILTERING #####################
############################################################

# We are NOT automatically removing rare ASVs here.
#
# DADA2 has already attempted to distinguish biological
# sequence variants from sequencing errors.
#
# Additional abundance or prevalence filtering may still be
# useful for some analyses, but it should be justified by the
# biological question and statistical approach.
#
# For example, the following would remove ASVs observed only
# once across the ENTIRE dataset:
#
# qiime feature-table filter-features \
#   --i-table filtered-table.qza \
#   --p-min-frequency 2 \
#   --o-filtered-table filtered-table-min2.qza
#
# Or, ASVs could be required to occur in a minimum number of
# samples using --p-min-samples.
#
# We will leave the ASV table unfiltered here.


############################################################
############ OPTIONAL SAMPLE FILTERING ######################
############################################################

# Samples can also be selected using metadata.
#
# For example:
#
# qiime feature-table filter-samples \
#   --i-table filtered-table.qza \
#   --m-metadata-file "$METADATA" \
#   --p-where "[sample-type] = 'sediment'" \
#   --o-filtered-table sediment-only-table.qza
#
# Sample filtering should reflect the experimental design,
# not whether removing samples makes an ordination look
# "better."


############################################################
################ INSPECT FINAL TABLE #########################
############################################################

# Examine sequencing depth and the number of ASVs retained
# after filtering.
#
# This visualization is particularly important before
# selecting a rarefaction depth.

qiime feature-table summarize \
  --i-table filtered-table.qza \
  --m-sample-metadata-file "$METADATA" \
  --o-visualization filtered-table.qzv


############################################################
################ TAXONOMIC COMPOSITION ######################
############################################################

# Generate an interactive stacked taxonomic bar plot.
#
# This is useful for exploring community composition at
# different taxonomic levels.
#
# Remember:
#
# The relative height of a taxon in this plot represents
# relative sequence abundance, NOT directly the relative
# abundance of cells or biomass in the environment.

qiime taxa barplot \
  --i-table filtered-table.qza \
  --i-taxonomy "$TAXONOMY" \
  --m-metadata-file "$METADATA" \
  --o-visualization taxa-bar-plots.qzv


############################################################
################## ALPHA RAREFACTION ########################
############################################################

# Sequencing depth differs among samples.
#
# Alpha rarefaction curves help us ask whether estimates of
# within-sample diversity begin to stabilize as sequencing
# depth increases.
#
# IMPORTANT:
#
# The maximum depth should be selected after examining
# filtered-table.qzv.
#
# 17,559 reads is shown here because this was the sampling
# depth used for this Moorea example.
#
# This is NOT a universal or recommended sequencing depth.

qiime diversity alpha-rarefaction \
  --i-table filtered-table.qza \
  --i-phylogeny "$TREE" \
  --p-max-depth 17559 \
  --m-metadata-file "$METADATA" \
  --o-visualization alpha-rarefaction.qzv


############################################################
################ CHOOSE SAMPLING DEPTH ######################
############################################################

# QIIME 2's core diversity pipeline rarefies all samples to
# the same sequencing depth before calculating these metrics.
#
# Choosing this value involves a tradeoff:
#
#   lower depth  -> retain more samples, discard more reads
#
#   higher depth -> retain more reads per sample, but lose
#                   samples that do not reach that depth
#
# The choice should be informed by:
#
#   filtered-table.qzv
#   alpha-rarefaction.qzv
#   the experimental design
#
# For the Moorea dataset, we use:

SAMPLING_DEPTH=17559


############################################################
################ CORE DIVERSITY METRICS #####################
############################################################

# This pipeline rarefies the table and calculates several
# commonly used ecological diversity metrics.
#
# ALPHA DIVERSITY includes:
#
#   observed features
#   Shannon diversity
#   Pielou's evenness
#   Faith's phylogenetic diversity
#
# BETA DIVERSITY includes:
#
#   Jaccard
#   Bray-Curtis
#   unweighted UniFrac
#   weighted UniFrac
#
# It also performs PCoA and generates interactive Emperor
# ordination plots for the beta-diversity metrics.

qiime diversity core-metrics-phylogenetic \
  --i-phylogeny "$TREE" \
  --i-table filtered-table.qza \
  --p-sampling-depth "$SAMPLING_DEPTH" \
  --p-n-jobs-or-threads "$SLURM_CPUS_PER_TASK" \
  --m-metadata-file "$METADATA" \
  --output-dir core-metrics-results


############################################################
################### ALPHA DIVERSITY #########################
############################################################

# alpha-group-significance compares alpha diversity among
# categories in the sample metadata.
#
# This produces interactive plots and non-parametric
# statistical comparisons.
#
# Remember that different alpha-diversity metrics measure
# different properties of a community.


# OBSERVED ASVs
#
# How many different ASVs were detected?

qiime diversity alpha-group-significance \
  --i-alpha-diversity core-metrics-results/observed_features_vector.qza \
  --m-metadata-file "$METADATA" \
  --o-visualization core-metrics-results/observed-features-group-significance.qzv


# SHANNON DIVERSITY
#
# Incorporates both richness and evenness.

qiime diversity alpha-group-significance \
  --i-alpha-diversity core-metrics-results/shannon_vector.qza \
  --m-metadata-file "$METADATA" \
  --o-visualization core-metrics-results/shannon-group-significance.qzv


# FAITH'S PHYLOGENETIC DIVERSITY
#
# Incorporates the amount of phylogenetic branch length
# represented within each sample.

qiime diversity alpha-group-significance \
  --i-alpha-diversity core-metrics-results/faith_pd_vector.qza \
  --m-metadata-file "$METADATA" \
  --o-visualization core-metrics-results/faith-pd-group-significance.qzv


# PIELOU'S EVENNESS
#
# Describes how evenly sequences are distributed among ASVs.

qiime diversity alpha-group-significance \
  --i-alpha-diversity core-metrics-results/evenness_vector.qza \
  --m-metadata-file "$METADATA" \
  --o-visualization core-metrics-results/evenness-group-significance.qzv


############################################################
#################### BETA DIVERSITY #########################
############################################################

# Beta diversity describes differences in community
# composition among samples.
#
# The core-metrics pipeline has already generated:
#
#   Bray-Curtis
#   Jaccard
#   weighted UniFrac
#   unweighted UniFrac
#
# distance matrices, PCoA coordinates, and Emperor plots.
#
# You therefore DO NOT need to run "qiime emperor plot"
# separately unless you want to generate a new/custom plot.


############################################################
####################### PERMANOVA ###########################
############################################################

# PERMANOVA can test whether community composition differs
# among groups.
#
# Here we use Bray-Curtis dissimilarity and ask whether
# communities differ among Moorea sites.
#
# Change site_number to another categorical metadata column
# to test another grouping variable.

qiime diversity beta-group-significance \
  --i-distance-matrix core-metrics-results/bray_curtis_distance_matrix.qza \
  --m-metadata-file "$METADATA" \
  --m-metadata-column site_number \
  --p-method permanova \
  --p-pairwise \
  --o-visualization core-metrics-results/bray-curtis-site-permanova.qzv


############################################################
######################## PERMDISP ###########################
############################################################

# A significant PERMANOVA result can reflect differences in
# group centroids, differences in within-group dispersion,
# or both.
#
# PERMDISP evaluates whether dispersion differs among groups.
#
# This should be considered alongside the PERMANOVA result.

qiime diversity beta-group-significance \
  --i-distance-matrix core-metrics-results/bray_curtis_distance_matrix.qza \
  --m-metadata-file "$METADATA" \
  --m-metadata-column site_number \
  --p-method permdisp \
  --o-visualization core-metrics-results/bray-curtis-site-permdisp.qzv


############################################################
############## MORE COMPLEX ECOLOGICAL MODELS ###############
############################################################

# beta-group-significance performs a ONE-FACTOR comparison.
#
# Real ecological experiments often contain several
# explanatory variables, covariates, interactions, blocks,
# repeated sampling, or other aspects of experimental design.
#
# QIIME 2 also provides a multi-factor PERMANOVA interface:
#
# qiime diversity adonis \
#   --i-distance-matrix core-metrics-results/bray_curtis_distance_matrix.qza \
#   --m-metadata-file "$METADATA" \
#   --p-formula "site_number+OTHER_VARIABLE" \
#   --p-n-jobs "$SLURM_CPUS_PER_TASK" \
#   --o-visualization core-metrics-results/bray-curtis-adonis.qzv
#
# For this workshop, however, we will perform more flexible
# ecological analyses in R using packages such as vegan.


############################################################
#################### EXPORT FOR R ###########################
############################################################

# QIIME 2 artifacts can be exported into standard file
# formats for analysis in other software.
#
# We will export:
#
#   1. ASV abundance table
#   2. taxonomy
#   3. phylogenetic tree


mkdir -p exported-data


# Export ASV table.
#
# This produces a BIOM file.

qiime tools export \
  --input-path filtered-table.qza \
  --output-path exported-data/asv-table


# Convert the BIOM table to a human-readable TSV file.
#
# "biom" is normally included in the QIIME 2 environment.

biom convert \
  -i exported-data/asv-table/feature-table.biom \
  -o exported-data/asv-table.tsv \
  --to-tsv


# Export taxonomy.
#
# This generates taxonomy.tsv.

qiime tools export \
  --input-path "$TAXONOMY" \
  --output-path exported-data/taxonomy


# Export the phylogenetic tree.
#
# This generates a Newick-format tree.

qiime tools export \
  --input-path "$TREE" \
  --output-path exported-data/tree


############################################################
######################## FINISHED ###########################
############################################################

echo ""
echo "========================================"
echo "QIIME 2 ecological analyses complete."
echo ""
echo "Important outputs:"
echo ""
echo "  filtered-table.qzv"
echo "  taxa-bar-plots.qzv"
echo "  alpha-rarefaction.qzv"
echo "  core-metrics-results/"
echo "  exported-data/"
echo ""
echo "The exported data can now be analyzed in R."
echo "========================================"
echo ""


conda deactivate
